Revert "mesa: llvm-16 support"
Causes problems with rust bindgen for rusticl, or something like that:
/<<PKGBUILDDIR>>/include/./CL/cl_platform.h:362:10: fatal error: 'stddef.h' file not found
thread 'main' panicked at 'Unable to generate bindings: ClangDiagnostic("/<<PKGBUILDDIR>>/include/./CL/cl_platform.h:362:10: fatal error: 'stddef.h' file not found\n")', src/main.rs:48:36

This reverts commit 366174b62309ede03babe145bdcb0c763e50c83b.